config/routes.rb
Rails.application.routes.draw do

  resources :students, path_names: {:new => 'sign_up'}, :controller => "registrations", :type => "Student", only: [:new, :create]
  resources :teachers, :controller => "registrations", :type => "Teacher",  only: [:new, :create]

  scope constraints: lambda { |r| r.env['warden'].user.nil? } do
    match "/login", to: "sessions#new", via: :get, as: "login"
  end

  match '/logout', to: 'sessions#destroy', via: [:delete], as: "logout"
  
  resources :sections do
    member do
      get 'edit_template'
    end
  end

  resources :courses do
    member do
      get 'structure'
    end
  end

  resources :page_templates
  resources :sessions, only: [:create]

  resources :users, path: '/', except: [:index, :new, :create, :destroy] do
    member do
      get 'dashboard'
      get 'settings'
      post 'update_settings'

    end
  end

  

  root to: 'static_pages#home'
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :course
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_filter :authenticate_user!, only: [:index]
  before_filter :authenticate_teacher!, only: [:new, :create, :edit, :update, :destroy]
  layout "app_ember"
  
  def index
    @sections = current_user.sections
  end
  
  def new
    @section = Section.new()
  end

  def create
    
    @section = current_user.sections.create(safe_params)
    if @secion.save
      flash.now.notice = "new template created"
      redirect_to sections_path()
  else
      flash.now.alert = "failed"
      redirect_to sections_path()
    end
  end

  def edit_template
    section = Section.find(params[:id])
    @template = section.page_template.uri
  end

  private

    def safe_params
      params.require(:section).permit(:title, :note, :page_template_id)
    end
end

app/views/sections/edit_template.html.erb
  <%= render partial: @template %>

app/views/sections/index.html.erb
<% if @sections.any? %>
  <% @sections.each do |section| %>
  <div class="media-item">
    <%= image_tag section.page_template.thumbnail.url() %>
    <%= section.title %>
  </div>
  <% end %>
<% else %>
  <div class="no-content">
    You Don't Have Any Course Sections, <%= link_to("Start a New One Now", new_section_path()) %>
  </div>

<% end %>

app/views/sections/new.html.erb
<div id="new-media">

  <%= form_for @section, url: { action: 'create' }, html:{ id: "", class: "" } do |f| %>
    <h2>Select a template that you would like to work with.</h2>
    <div class="template-list mbs">

      <% PageTemplate.all.each do |pt| %>
        <div class="template-item">
          <%= f.radio_button :page_template_id, pt.id %>
          <label for=<%= "media_page_template_id_#{pt.id}" %> class="templates">
            <%= image_tag pt.thumbnail.url() %>
            <div class="template-details vertical-center">
              <div>
                <div class='description'>
                  <%= pt.descriptions  %>
                </div>
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 50 50" enable-background="new 0 0 50 50" xml:space="preserve">
                <path d="M25,5C13.973,5,5,13.973,5,25s8.973,20,20,20c11.029,0,20-8.973,20-20S36.029,5,25,5z M36.824,26.98
                  c0,1.346-1.09,2.436-2.434,2.436h-4.976v4.975c0,1.346-1.092,2.435-2.437,2.435h-3.961c-1.346,0-2.436-1.089-2.436-2.435v-4.975
                  h-4.975c-1.344,0-2.435-1.09-2.435-2.436V23.02c0-1.347,1.091-2.437,2.435-2.437h4.975v-4.976c0-1.344,1.09-2.434,2.436-2.434h3.961
                  c1.345,0,2.437,1.09,2.437,2.434v4.976h4.976c1.344,0,2.434,1.09,2.434,2.437V26.98z"/>
                </svg>
              </div>
            </div>
          </label>
          <div class="name">
            <%= pt.name %>
          </div>
        </div>
        
      <% end %>
    </div>
   

    <div class="media-details clearfix">
      <fieldset style="width: 30%;">
        <%= f.text_field :title, class: "form-control", placeholder: "Enter Section Title"  %>
      </fieldset>


      <fieldset style="width: 65%;">
        <%= f.text_field :note, class: "form-control", placeholder: "Enter Additional Notes" %>
      </fieldset>
      <fieldset style="width: 2%;">
        <button type="submit" class="btn">
          <svg  xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 32 32"  xml:space="preserve">

            <path d="M30.277,1.722C29.168,0.611,27.691,0,26.121,0c-1.569,0-3.045,0.61-4.154,1.72L4.295,19.291
            C4.19,19.395,4.11,19.52,4.06,19.658l-4,11c-0.129,0.355-0.046,0.756,0.215,1.031C0.467,31.891,0.73,32,1,32
            c0.098,0,0.196-0.014,0.293-0.044l9.949-3.052c0.156-0.047,0.298-0.133,0.414-0.248l18.621-18.621C31.389,8.926,32,7.448,32,5.878
            C31.999,4.309,31.389,2.832,30.277,1.722z M10.093,27.165l-3.724,1.144c-0.217-0.637-0.555-1.201-1.016-1.662
            c-0.401-0.4-0.866-0.709-1.356-0.961L5.7,21H8v2c0,0.553,0.447,1,1,1h1.765L10.093,27.165z M24.812,12.671L12.629,24.855
            l0.35-1.647c0.062-0.296-0.012-0.603-0.202-0.837C12.587,22.136,12.302,22,12,22h-2v-2c0-0.552-0.448-1-1-1H7.423L19.316,7.175
            l0.011,0.011c0.733-0.733,1.707-1.136,2.743-1.136c1.035,0,2.01,0.403,2.742,1.136c0.731,0.733,1.137,1.707,1.137,2.743
            C25.949,10.965,25.546,11.938,24.812,12.671z M28.863,8.621L27.93,9.554c-0.09-1.429-0.683-2.761-1.703-3.782
            c-1.021-1.022-2.355-1.614-3.787-1.703l0.937-0.931l0.002-0.002C24.111,2.403,25.085,2,26.121,2s2.01,0.403,2.742,1.136
            C29.596,3.869,30,4.843,30,5.878C30,6.915,29.598,7.889,28.863,8.621z M22.293,8.293l-10,10c-0.391,0.391-0.391,1.023,0,1.414
            C12.488,19.902,12.744,20,13,20s0.511-0.098,0.707-0.293l10-10c0.391-0.391,0.391-1.023,0-1.414S22.684,7.902,22.293,8.293z"/>

          </svg>
        </button>
      </fieldset>
    </div>
  <% end %>
</div>