config/routes.rb
Rails.application.routes.draw do

  resources :students, path_names: {:new => 'sign_up'}, :controller => "registrations", :type => "Student", only: [:new, :create]
  resources :teachers, :controller => "registrations", :type => "Teacher",  only: [:new, :create]

  scope constraints: lambda { |r| r.env['warden'].user.nil? } do
    match "/login", to: "sessions#new", via: :get, as: "login"
  end

  match '/logout', to: 'sessions#destroy', via: [:delete], as: "logout"
  
  resources :sections do
    member do
      get 'edit_template'
    end
  end

  resources :courses do
    member do
      get 'structure'
    end
  end

  resources :page_templates
  resources :sessions, only: [:create]

  resources :users, path: '/', except: [:index, :new, :create, :destroy] do
    member do
      get 'dashboard'
      get 'settings'
      post 'update_settings'

    end
  end

  

  root to: 'static_pages#home'
end

app/models/admin.rb
class Admin < User

  def assign_group
    self.group_id = 1
    return self
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  
  has_many :sections, dependent: :destroy
  belongs_to :user

  PaymentMethods = ['None', 'One Time', 'Monthly', 'Annually']
  Discount = ['None', '10%', '20%', '30%', '40%', '50%']
  CourseType =  [
      'eBook',
      'Video Tutorial',
      'Seminar',
      'Webinar',
      'Single Module',
      'Multi Modules'
    ]
  attr_accessor :start_hour, :start_minute, :start_period,
   :end_hour, :end_minute, :end_period 


  has_attached_file :thumbnail, :default_url => "no-image.png"
  validates_attachment_content_type :thumbnail, :content_type => /\Aimage\/.*\Z/
  

  def self.course_types
   
  end


end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/page_template.rb
class PageTemplate < ActiveRecord::Base
  

  has_attached_file :thumbnail, :default_url => "no-image.png"
  validates_attachment :thumbnail, :presence => true,
  :content_type => { :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

  def uri
    "page_templates/templates/#{name.downcase}"
  end

  def self.categories
    [
      'Ebook',
      'Video',
      'Other'
    ]
  end
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :course
end

app/models/student.rb
class Student < User

  def assign_group
    self.group_id = 3
    return self
  end

end

app/models/teacher.rb
class Teacher < User

  def assign_group
    self.group_id = 2
    return self
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :login

  serialize :profile
  has_many :courses

  has_attached_file :display_image, :default_url => "no-image.png"
  
  validates :username, presence: true, format: { with: /\A[a-zA-Z0-9]+\Z/ },
    uniqueness: { case_sensitive: false }

  has_secure_password
  
  # Overwrite to_params
  def to_param
    username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def current_user
    @current_user ||= warden.user(:user)
  end

  helper_method :current_user

  def authenticate_user!
    unless warden.authenticated?
      set_flash_message :alert, :restricted, {scope: "failure"}
      redirect_to root_path
    end
  end

  def authenticate_student!
    unless warden.authenticated? && warden.user(:user).kind_of?(Student)
      set_flash_message :alert, :restricted, {scope: "failure"}
      redirect_to root_path
    end
  end 

  def authenticate_teacher!
    unless warden.authenticated? && warden.user(:user).kind_of?(Teacher)
      set_flash_message :alert, :restricted, {scope: "failure"}
      redirect_to root_path
    end
  end

  protected

    def resource 
      @resource ||= ( params[:type].constantize )
    end

    def resource_name
      @resource_name ||= params[:type].downcase.to_sym
    end
    
    def warden
      env['warden']
    end

    def set_flash_message(key, kind, options = {})
      message = find_message(kind, options)
      if options[:now]
        flash.now[key] = message if message.present?
      else
        flash[key] = message if message.present?
      end
    end

    # Get message for given
    def find_message(kind, options = {})
      options[:scope] ||= i18n_scope
      I18n.t(kind, options)
    end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  layout 'app_ember'

  before_filter :authenticate_teacher!

  
  def index

    @courses = current_user.courses

  end

  def new
    @course = Course.new()
  end

  def create
    @course = current_user.courses.create(newCourseParams)
    if @course.save()
      respond_to do |format|
        format.html { redirect_to courses_path() }
        format.json { render json: @course, root: false }
      end
    else
      redirect_to :back
    end
  end

  def structure
    
  end

  def destroy
    course = Course.find(params[:id]).destroy
    redirect_to :back
  end


  private

    def newCourseParams
      params.require(:course).permit(:title)
    end

    def safeParams
      startDate = convertDateTime(params[:start_date], params[:start_hour], params[:start_minute], params[:start_period])
      endDate = convertDateTime(params[:end_date], params[:end_hour], params[:end_minute], params[:end_period]) 


      params.require(:course).permit(:title, :thumbnail, :course_category_id, :description, :start_date, :end_date,
        :prerequisites, :student_limit, :max_student, :course_type, :note, :price, 
        :payment_method, :discount).merge(start_date: startDate, end_date: endDate)
      
    end

    def convertDateTime(date, hour, minute, period)
      time = (period == "AM") ? hour : (hour.to_i + 12)
      date += " #{time}:#{minute}"
      newDate = Time.zone.parse(date)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_filter :authenticate_user!, only: [:index]
  before_filter :authenticate_teacher!, only: [:new, :create, :edit, :update, :destroy]
  layout "app_ember"
  
  def index
    @sections = current_user.sections
  end
  
  def new
    @section = Section.new()
  end

  def create
    
    @section = current_user.sections.create(safe_params)
    if @secion.save
      flash.now.notice = "new template created"
      redirect_to sections_path()
  else
      flash.now.alert = "failed"
      redirect_to sections_path()
    end
  end

  def edit_template
    section = Section.find(params[:id])
    @template = section.page_template.uri
  end

  private

    def safe_params
      params.require(:section).permit(:title, :note, :page_template_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    flash.now[:alert] = warden.message if warden.message.present?  
  end

  def create
    warden.authenticate!(scope: :user)
    redirect_to dashboard_user_path(current_user), notice: "Logged in!"
  end

  def destroy
    warden.logout
    redirect_to root_url, notice: "Logged out!"
  end

  protected

    def i18n_scope
      'sessions'
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  

  def show
    render layout: "app_ember"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  layout "app_ember"
  before_filter :authenticate_user!

  def show
   @user = User.find_by_username(params[:id])
  end

  def settings

  end

  def dashboard
  end

  def update_settings
    @user = User.find_by_username(params[:id])
    @user.update(profile: params[:profile])
    redirect_to :back
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Helper Method for Page Title
  def page_title(title)
    base_title = "Successfulnes"
    if title.empty?
      base_title
    else
      "#{base_title} | #{title}"
    end
  end

  # Helper to render Serialized data inline
  def json_for(obj, options = {})
    options[:scope] ||= self
    options[:url_options] ||= url_options
    ActiveModel::Serializer.serializer_for(obj).new(obj, options).to_json
  end


  def user_signed_in?
    !!current_user
  end

  def hours
    (1..12).to_a
  end

  def minutes
    [ "00", "15", "30", "45" ]
  end

  def period
    [ "AM", "PM" ]
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_side_large.html.erb
<div id="large-nav">
  <div class="content">
    <div class="top">
      <%= link_to "", "#", id: "logo" %>
      <form action="/search" id="sidebar_search" method="get">
        <input placeholder="Search" data-bindattr-598="598" autocomplete="off" class="search_input" id="sidebar_query" name="query" tabindex="99">
      </form>
    </div>

    <div class="middle" >

      <div class="tse-scrollable wrapper1">
        <div class="tse-content">

          <div class="nav_section" id="nav_personal">
            <ul>
              <li>
                <div id="you">
                  <span class="username">
                    {{user}}
                  </span>
                  <%= link_to "#", class: "logout", method: "delete" do %>
       
                    <svg class="svg-nav_logout" height="18px" version="1.1" viewBox="0 0 18 18" width="18px" x="0px" y="0px">
                      <path clip-rule="evenodd" d="M16,9l-6,6v-4H6V7h4V3L16,9z M4,13h4v2H2v-2V5V3h6v2H4V13z" fill-rule="evenodd"></path>
                    </svg>
                  <% end -%>

                   <%= link_to "#", class: "settings" do %>
                    <svg class="svg-nav_settings" height="18px" version="1.1" viewBox="0 0 18 18" width="18px" x="0px" y="0px">
                      <path clip-rule="evenodd" d="M15.03,5.091v4.878l-2,2H8.151l-3.061,3.061L2.97,12.908l3.061-3.06V4.97l2-2h4.879L8.97,6.909l2.121,2.121L15.03,5.091z" fill-rule="evenodd"></path>
                    </svg>
                  <% end -%>
                </div>
              </li>

              <li class="selected" data-name="profile" title="Profile">
                <a data-href="/stwitch007/profile" href="/stwitch007/profile" class="group">
                  <span class="filter_icon">
                    <svg class="svg-nav_profile" height="18px" version="1.1" viewBox="0 0 18 18" width="18px" x="0px" y="0px">
                      <path clip-rule="evenodd" d="M2,16v-1l3-3h3L5,9V2h8v7l-3,3h3l3,3v1H2z" fill-rule="evenodd"></path>
                    </svg>
                  </span>
                  <span class="title">Profile</span>
                </a>
              </li>

              <li>
                <a href="/messages/inbox" id="large_messages">
                  <span class="filter_icon">
                    <svg class="svg-nav_messages" height="18px" version="1.1" viewBox="0 0 18 18" width="18px" x="0px" y="0px">
                      <path clip-rule="evenodd" d="M1,15V3h16v12H1z M15.354,5.354l-0.707-0.707L9,10.293L3.354,4.646L2.646,5.354L6.293,9l-3.646,3.646l0.707,0.707L7,9.707l1.646,1.646h0.707L11,9.707l3.646,3.646l0.707-0.707L11.707,9L15.354,5.354z" fill-rule="evenodd"></path>
                    </svg>
                  </span>
                  <span class="title">Messages</span>
                  <span style="display: none;" class="total_count js-unread_message_count"></span>
                </a>
              </li>

              <li>
                <a href="/messages/inbox" id="large_messages">
                  <span class="filter_icon">
                    <svg x="0px" y="0px" viewBox="0 0 420.609 420.609">
                      <path d="M350.035,275.014c-3.38-8.072-11.508-13.254-19.263-16.434l-25.851-11.898c-0.028-18.977-0.207-113.495-0.101-123.436
                        c0.153-15.465-1.69-29.278-5.754-41.227l32.188-11.63l0.074,29.738l-2.188-0.001c-1.521-0.134-2.865,0.96-3.04,2.478
                        l-2.833,24.559c-0.088,0.747,0.135,1.493,0.609,2.081c0.473,0.585,1.166,0.963,1.914,1.026l22.482-0.008
                        c0.756-0.085,1.445-0.446,1.912-1.034c0.48-0.586,0.693-1.344,0.609-2.094c-0.567-4.823-1.132-9.639-1.693-14.462l-1.174-10.095
                        c-0.179-1.505-1.526-2.601-3.044-2.466l-2.188,0.003l0.047-33.883l1.144-0.415l3.806-1.375c3.227-1.164,5.372-4.225,5.372-7.65
                        c0-3.427-2.146-6.488-5.372-7.653L213.071,0.488c-1.789-0.65-3.744-0.65-5.531,0L72.915,49.139
                        c-3.227,1.165-5.374,4.227-5.374,7.653s2.147,6.486,5.374,7.65l48.819,17.644c-4.263,12.257-6.203,26.431-6.044,42.259
                        l0.002,122.333L89.837,258.58c-7.757,3.18-15.383,8.016-19.263,16.434c0,0-56.998,145.596-26.081,145.596h331.62
                        C407.034,420.607,350.035,275.014,350.035,275.014z M262.119,262.51c0,0-43.391,14.377-51.748,64.875
                        c-0.022,0.133-0.106,0.133-0.129,0c-8.359-50.498-51.748-64.875-51.748-64.875l28.439-28.242
                        c-40.093-17.982-50.755-79.127-50.755-79.127c-2.266-8.839-2.539-14.885-2.539-14.885c20.073-1.367,90.128-7.401,94.917-30.111
                        c6.603,12.2,41.561,42.857,55.705,45.185c0,0-13.729,60.463-51.229,78.895L262.119,262.51z"/>
                    </svg>
                  </span>
                  <span class="title">Students</span>
                  <span style="display: none;" class="total_count js-unread_message_count"></span>
                </a>
              </li>

              <li>
                <%= link_to courses_path() do %>
                  <span class="filter_icon">
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 512 512">
                      <path d="M288.117,144.635l121.355-40.716l101.792,303.392l-121.355,40.717L288.117,144.635z M0,448h128V96H0V448z M32,160h64v32H32
                      V160z M160,448h128V96H160V448z M192,160h64v32h-64V160z"/>
                    </svg>

                  </span>
                  <span class="title">Courses</span>
                  <span style="display: none;" class="total_count js-unread_message_count"></span>
                <% end %>
              </li>

            </ul>
            <div class="nav-divider"></div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_side_nav.html.erb
  
<script type="text/x-handlebars" data-template-name="components/left-toggle-button">
  <a id="left-close">
    <span>Show/Hide</span>
  </a>

</script>

<script type="text/x-handlebars" data-template-name="components/left-menu">
  {{left-toggle-button action="toggle"}}
  <%= render 'layouts/side_large' %>
  <%= render 'layouts/side_small' %>
</script>

app/views/layouts/_side_small.html.erb
<div id="small-nav">
  <div class="content">
    <ul class="isLoggedIn" data-bindattr-659="659" id="nav_small">
      <li class="" id="small_home">
        <a original-title="" class="home_icon" href="/">
        </a>
      </li>

      <div class="divider"></div>

      <li class="" id="small_search">
        <a original-title="Search" class="filter_icon" href="/directory">
          <svg class="svg-nav_search" height="18px" version="1.1" viewBox="0 0 18 18" width="18px" x="0px" y="0px">
            <path clip-rule="evenodd" d="M16.707,15.293l-1.414,1.414l-4.825-4.825C9.487,12.58,8.295,13,7,13c-3.313,0-6-2.687-6-6s2.687-6,6-6s6,2.687,6,6c0,1.295-0.42,2.487-1.118,3.468L16.707,15.293z M7,3C4.791,3,3,4.791,3,7s1.791,4,4,4s4-1.791,4-4S9.209,3,7,3z" fill-rule="evenodd"></path>
          </svg>
        </a>
      </li>

      <li class="js-nav-menu">
        <ul class="game_filters" id="menu_defaults">
          <li class="clearfix" data-bindattr-662="662" data-name="following">
            <a original-title="Following" data-bindattr-663="663" data-ember-action="664" class="clearfix" data-href="following" href="/directory/following">
              <span class="filter_icon">
                <svg class="svg-nav_profile" height="18px" version="1.1" viewBox="0 0 18 18" width="18px" x="0px" y="0px">
                  <path clip-rule="evenodd" d="M2,16v-1l3-3h3L5,9V2h8v7l-3,3h3l3,3v1H2z" fill-rule="evenodd"></path>
                </svg>
              </span>
            </a>
          </li>

          <li class="game_filter clearfix" data-bindattr-665="665" data-name="games">
            <a original-title="Browse Games" class="clearfix" data-href="." href="/directory">
              <span class="filter_icon">
                <svg class="svg-nav_messages" height="18px" version="1.1" viewBox="0 0 18 18" width="18px" x="0px" y="0px">
                  <path clip-rule="evenodd" d="M1,15V3h16v12H1z M15.354,5.354l-0.707-0.707L9,10.293L3.354,4.646L2.646,5.354L6.293,9l-3.646,3.646l0.707,0.707L7,9.707l1.646,1.646h0.707L11,9.707l3.646,3.646l0.707-0.707L11.707,9L15.354,5.354z" fill-rule="evenodd"></path>
                </svg>
              </span>
            </a>
          </li>
        </ul>
      </li>

    </ul>

  </div>
</div>

app/views/layouts/_top_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= button_tag "#", class: "navbar-toggle", data: {toggle: "collapse", target: "#32a"} do %>
        <span class="sr-only"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      <% end %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Browse", "#" %>
        </li>
        <li>
          <%= link_to "About", "#" %>
        </li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle", data: {toggle: "dropdown"} do %>
              <%= current_user.username %>
              <span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Dashboard", dashboard_user_path(current_user) %>
              </li>

              <li>
                <%= link_to "Profile", user_path(current_user) %>
              </li>
                <li class="divider"></li>
              <li>
                <%= link_to "Log Out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to "Sign Up", new_student_path, class: "btn btn-top-nav btn-signup" %>
          </li>
          <li>
            <%= link_to "Log In", login_path, class: "btn btn-top-nav btn-signin" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/app_ember.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]> <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]> <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]> ><! <![endif]-->
<html lang="en">
<!-- <![endif] -->
  <head>
    <meta charset="utf-8">
    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
    <!-- Set the viewport width to device width for mobile -->
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href='http://fonts.googleapis.com/css?family=Press+Start+2P' rel='stylesheet' type='text/css'>
    
    <title><%= page_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "ember.init" %>
    <%= yield :head %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  </head>

  <body>
    <script type="text/x-handlebars" data-template-name="application">
      {{outlet 'modal'}}
      <div class="main-wrapper">
        <div id="left-menu" {{bind-attr class="isOpenLeft:open:closed"}}>
          {{left-menu user="<%=  current_user ? current_user.username : 'Not Logged in'  %>" open="openLeft" close="closeLeft" isOpen=isOpenLeft }}
        </div>
        <div id="main-content" {{bind-attr class="isOpenLeft::extended isOpenRight::extendedRight"}}>
    
          <%= yield %>
      
        </div>
    
      </div>
    </script>

    <%= render 'layouts/side_nav' %>
    <%= render 'shared/ember_views' %>
    <%= yield :footer %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]> <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]> <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]> ><! <![endif]-->
<html lang="en">
<!-- <![endif] -->
  <head>
    <meta charset="utf-8">
    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
    <!-- Set the viewport width to device width for mobile -->
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= page_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  </head>

  <body>
    <head>
      <%= render 'layouts/top_nav' %>
    </head>
     <%= render 'shared/flash_notice' %>

    <div class="main-content-wrapper row">
      <div class="container">
        <%= yield %>
      </div>
    </div>
    
  </body>
</html>

app/views/shared/_ember_views.html.erb
<script type="text/x-handlebars" data-template-name="components/editable-div">
  {{yield}}
</script>

<script type="text/x-handlebars" data-template-name="components/editable-header">
  {{yield}}
</script>


<script type="text/x-handlebars" data-template-name="modal">
  {{#modal-dialog action="close"}}
     <div class="modal-header">
      <button type="button" class="close" {{action "close"}}><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">{{title}}</h4>
      </div>
      <div class="modal-body">
        <p>{{content}}</p>
      </div>
  {{/modal-dialog}}
</script>


<script type="text/x-handlebars" data-template-name="edit-thumb">
  {{#modal-dialog action="close" confirmBotton="Crop"}}
      <div class="modal-body edit-thumb">
        {{content}}
      </div>
  {{/modal-dialog}}
</script>

<script type="text/x-handlebars" data-template-name="components/modal-dialog">
  <div class="overlay" {{action "close"}}> </div>
  <div class="modal-dialog">
    <div class="modal-content">
      {{yield}}
      <div class="modal-footer">
        <button type="button" class="btn btn-default" {{action "close"}}>Close</button>
        <button type="button" class="btn btn-theme-dark">{{confirmBotton}}</button>
      </div>
    </div>
  </div>
</script>


<script type="text/x-handlebars" data-template-name="_loader">
  <div class="wrap">
    <div class="loading">
      <span class="title">loading</span>
      <span class="text">Ah.....</span>
    </div>
  </div>
</script>

<!-- Test -->
<script type="text/x-handlebars" data-template-name="course-module">
  <div class=""> 
    {{yield}}
  </div>
</script>

app/views/shared/_flash_notice.html.erb
<% flash.each do |k, v| %>
  <% Rails.logger.warn "#{flash}" %>
  <div class="alert-success alert alert-dismissible">
    <%= v %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  </div>
<% end %>

app/views/shared/_modal.html.erb
<script type="text/x-handlebars" data-template-name="modal">
  {{#modal-dialog action="close"}}
     <div class="modal-header">
      <button type="button" class="close" {{action "close"}}><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">{{title}}</h4>
      </div>
      <div class="modal-body">
        <p>{{content}}</p>
      </div>
  {{/modal-dialog}}
</script>

<script type="text/x-handlebars" data-template-name="components/modal-dialog">
  <div class="overlay" {{action "close"}}> 
  </div>
  <div class="modal-dialog">
    <div class="modal-content">
      {{yield}}
      <div class="modal-footer">
        <button type="button" class="btn btn-default" {{action "close"}}>Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</script>